name: Fetch IERS Data

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Fetch and process IERS data
        run: |
          python - <<EOF
          import pandas as pd
          import requests
          import json

          # Download the IERS Bulletin B data
          url = "ftp://hpiers.obspm.fr/iers/bul/bulb_new/bulletinb.txt"
          response = requests.get(url)
          with open("bulletinb.txt", "wb") as f:
              f.write(response.content)

          # Read the data into a pandas DataFrame
          df = pd.read_csv("bulletinb.txt", sep="\s+", header=None, comment=";", skiprows=1)
          df.columns = ["Year", "Month", "Day", "MJD", "x", "y", "UT1-UTC", "dX", "dY", "x_err", "y_err", "UT1_err", "X_err", "Y_err"]

          # Select relevant columns and convert to JSON
          points = df[["x", "y", "dX", "dY"]].to_dict(orient="records")
          with open("docs/volumetric_data.json", "w") as f:
              json.dump(points, f)
          EOF

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/volumetric_data.json
          git commit -m "Update volumetric data from IERS Bulletin B"
          git push
