name: Fetch IERS Bulletin A Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # optional: run daily at 02:00 UTC

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Fetch and process IERS data
        run: |
          python engine/fetch_iers_data.py --output docs/volumetric_data.json

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/volumetric_data.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update volumetric data from IERS Bulletin A"
            git push
          fi
