name: Fetch IERS Bulletin A Data

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Fetch and process IERS data
        run: |
          python - <<EOF
          import pandas as pd
          import requests
          import json

          # Download the IERS Bulletin A data
          url = "https://datacenter.iers.org/data/csv/bulletina.longtime.csv"
          response = requests.get(url)
          with open("bulletina.longtime.csv", "wb") as f:
              f.write(response.content)

          # Read the data into a pandas DataFrame
          df = pd.read_csv("bulletina.longtime.csv", header=0, comment=";", skiprows=1)

          # Select relevant columns and convert to JSON
          points = df[["x", "y", "dX", "dY"]].to_dict(orient="records")
          with open("docs/volumetric_data.json", "w") as f:
              json.dump(points, f)
          EOF

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/volumetric_data.json
          git commit -m "Update volumetric data from IERS Bulletin A"
          git push
