name: Update Volumetric Data

on:
  schedule:
    - cron: '0 2 * * *'  # every day at 02:00 UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy scipy

      # Step 4: Run fetch_iers_data.py
      - name: Run fetch_iers_data.py
        run: |
          python engine/fetch_iers_data.py --output volumetric_data.json
          ls -l   # confirm file exists

      # Step 5: Checkout gh-pages branch into subfolder
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      # Step 6: Move JSON into gh-pages/docs
      - name: Move JSON to gh-pages/docs
        run: |
          mkdir -p gh-pages/docs
          mv volumetric_data.json gh-pages/docs/volumetric_data.json

      # Step 7: Commit & push changes
      - name: Commit & push changes
        working-directory: gh-pages
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/volumetric_data.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update volumetric_data.json from IERS"
            git push origin gh-pages
