name: Update Volumetric Data

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily
  workflow_dispatch:      # manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: pip install pandas requests

      - run: python engine/fetch_iers_data.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/volumetric_data.json
          git commit -m "Update volumetric JSON from IERS data"
          git push
