# This workflow updates volumetric_data.json daily; replaces fetch_iers.yml
name: Update Volumetric Data

on:
  schedule:
    - cron: '0 2 * * *'  # daily at 02:00 UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout main branch (script lives here)
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main

      # Step 2: Checkout gh-pages branch (output goes here)
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          token: ${{ secrets.PAT_TOKEN }}   # fine-grained token with repo access
          path: gh-pages

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy

      # Step 5: Run fetch_iers_data.py and save into gh-pages/docs
      - name: Run data fetch
        working-directory: main/engine
        run: |
          python fetch_iers_data.py --output "../../gh-pages/docs/volumetric_data.json"

      # Step 6: Commit & push changes
      - name: Commit & push changes
        working-directory: gh-pages
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

          # Append test timestamp to verify commit/push chain
          echo "{\"last_test_run\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" >> docs/volumetric_data.json

          git add docs/volumetric_data.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update volumetric_data.json from IERS
Co-authored-by: Corvin Dhali <corvindhali@icloud.com>
Co-authored-by: GPT-5 <assistant@openai.com>"
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
          fi
