name: Update Volumetric Data

on:
  schedule:
    - cron: '0 2 * * *'  # every day at 02:00 UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy scipy

      - name: Run fetch_iers_data.py
        run: python engine/fetch_iers_data.py

      - name: Check for changes in volumetric_data.json
        id: git-check
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/volumetric_data.json
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Commit and push if JSON changed
        if: env.no_changes == 'false'
        run: |
          git commit -m "Update volumetric_data.json from IERS"
          git push origin main
